name: Build and Publish NuGet Packages

on:
  push:
    branches: [ develop, main ]
    paths:
      - '**/*.csproj'
      - '**/*.cs'
      - '.github/workflows/nuget-packages.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.csproj'
      - '**/*.cs'
      - '.github/workflows/nuget-packages.yml'
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version (e.g., 1.0.0)'
        required: false
        type: string
      publish_to_nuget:
        description: 'Publish to NuGet.org'
        required: false
        default: false
        type: boolean

env:
  DOTNET_VERSION: '9.0.x'
  BUILD_CONFIGURATION: 'Release'

permissions:
  contents: write       # Required to push commits back to repository
  actions: read         # Required to read workflow artifacts
  pull-requests: write  # Required to create pull requests

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.version.outputs.version }}
      should_publish: ${{ steps.publish_check.outputs.should_publish }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for GitVersion
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event.inputs.version }}" != "" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "release" ]; then
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        else
          # Auto-increment patch version ONLY for develop branch pushes
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            # Get current version from project file
            CURRENT_VERSION=$(grep -oE '<Version>[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?</Version>' affolterNET.Web.Core/affolterNET.Web.Core.csproj | sed -E 's/<\/?Version>//g')
            echo "Current version: $CURRENT_VERSION"
            
            # Parse version components
            MAIN_VERSION=$(echo "$CURRENT_VERSION" | cut -d'-' -f1)
            PRERELEASE=$(echo "$CURRENT_VERSION" | grep -oE '\-[a-zA-Z0-9.]+' || echo "")
            MAJOR=$(echo "$MAIN_VERSION" | cut -d'.' -f1)
            MINOR=$(echo "$MAIN_VERSION" | cut -d'.' -f2)
            PATCH=$(echo "$MAIN_VERSION" | cut -d'.' -f3)
            
            # Increment patch version
            NEW_PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
            
            # Add prerelease suffix if it existed
            if [ -n "$PRERELEASE" ]; then
              NEW_VERSION="$NEW_VERSION$PRERELEASE"
            fi
            
            echo "New version: $NEW_VERSION"
            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            # Use current version as-is for all other branches (main, feature, etc.)
            VERSION=$(grep -oE '<Version>[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?</Version>' affolterNET.Web.Core/affolterNET.Web.Core.csproj | sed -E 's/<\/?Version>//g')
            echo "Using existing version: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Update project versions
      run: |
        VERSION="${{ needs.build-and-test.outputs.version }}"
        echo "Using version: $VERSION"
        
        # Only update versions if they differ (for main branch, they should already be correct)
        if [ "${{ github.ref }}" != "refs/heads/main" ]; then
          echo "Updating project versions to: $VERSION"
          # Update version in all project files
          find . -name "*.csproj" -exec sed -i "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/g" {} \;
        else
          echo "Using existing versions from project files (main branch)"
        fi
        
        # Display current versions for verification
        echo "Current project versions:"
        find . -name "*.csproj" -exec grep -H "<Version>" {} \;

    - name: Check if should publish
      id: publish_check
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ] && [ "${{ github.event_name }}" == "push" ]; then
          echo "should_publish=true" >> $GITHUB_OUTPUT
          echo "Will publish packages (main branch push)"
        else
          echo "should_publish=false" >> $GITHUB_OUTPUT
          echo "Will not publish packages (not main branch push)"
        fi

    - name: Commit version changes
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push' && github.event.inputs.version == ''
      run: |
        NEW_VERSION="${{ steps.version.outputs.version }}"
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add and commit changes directly to develop
        git add *.csproj */*.csproj
        if git diff --staged --quiet; then
          echo "No version changes to commit"
        else
          git commit -m "chore: bump version to $NEW_VERSION"
          git push origin develop
          echo "Version bumped to $NEW_VERSION on develop branch"
        fi

    - name: Build projects
      run: |
        dotnet build affolterNET.Web.Core/affolterNET.Web.Core.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        dotnet build affolterNET.Web.Api/affolterNET.Web.Api.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        dotnet build affolterNET.Web.Bff/affolterNET.Web.Bff.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Run tests
      run: |
        # Run tests if test projects exist
        if find . -name "*Test*.csproj" -o -name "*.Tests.csproj" | grep -q .; then
          echo "Running tests..."
          dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal --logger trx --results-directory ./test-results
        else
          echo "No test projects found, skipping tests"
        fi

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./test-results/*.trx

  pack-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' && 
      (needs.build-and-test.outputs.should_publish == 'true' || 
       github.event_name == 'release' || 
       github.event_name == 'workflow_dispatch')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Update project versions
      run: |
        VERSION="${{ needs.build-and-test.outputs.version }}"
        echo "Setting version to: $VERSION"
        
        # Update version in all project files
        find . -name "*.csproj" -exec sed -i "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/g" {} \;

    - name: Switch to NuGet references
      run: |
        ./switch-references.sh nuget
        echo "Switched to NuGet package references for packaging"

    - name: Build projects
      run: |
        dotnet build affolterNET.Web.Core/affolterNET.Web.Core.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        dotnet build affolterNET.Web.Api/affolterNET.Web.Api.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        dotnet build affolterNET.Web.Bff/affolterNET.Web.Bff.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Pack NuGet packages
      run: |
        echo "Packing packages with version ${{ needs.build-and-test.outputs.version }}"
        
        # Pack Core package (must be first due to dependencies)
        dotnet pack affolterNET.Web.Core/affolterNET.Web.Core.csproj \
          --configuration ${{ env.BUILD_CONFIGURATION }} \
          --no-restore \
          --no-build \
          --output ./packages \
          --include-symbols \
          --include-source \
          -p:SymbolPackageFormat=snupkg
        
        # Pack Api package
        dotnet pack affolterNET.Web.Api/affolterNET.Web.Api.csproj \
          --configuration ${{ env.BUILD_CONFIGURATION }} \
          --no-restore \
          --no-build \
          --output ./packages \
          --include-symbols \
          --include-source \
          -p:SymbolPackageFormat=snupkg
        
        # Pack Bff package
        dotnet pack affolterNET.Web.Bff/affolterNET.Web.Bff.csproj \
          --configuration ${{ env.BUILD_CONFIGURATION }} \
          --no-restore \
          --no-build \
          --output ./packages \
          --include-symbols \
          --include-source \
          -p:SymbolPackageFormat=snupkg
        
        echo "Created packages:"
        ls -la ./packages/

    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./packages/*.nupkg

    - name: Upload symbol packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-symbol-packages
        path: ./packages/*.snupkg

    - name: Publish to NuGet.org
      if: |
        needs.build-and-test.outputs.should_publish == 'true' ||
        (github.event_name == 'release' && github.event.action == 'published') || 
        (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_nuget == 'true')
      run: |
        echo "Publishing packages to NuGet.org..."
        for package in ./packages/*.nupkg; do
          echo "Publishing $package"
          dotnet nuget push "$package" \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
        done
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    - name: Create release notes
      if: github.event_name == 'release'
      run: |
        echo "## NuGet Packages Published" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Version: ${{ needs.build-and-test.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Packages:" >> $GITHUB_STEP_SUMMARY
        echo "- affolterNET.Web.Core" >> $GITHUB_STEP_SUMMARY
        echo "- affolterNET.Web.Api" >> $GITHUB_STEP_SUMMARY
        echo "- affolterNET.Web.Bff" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Installation:" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo "dotnet add package affolterNET.Web.Core --version ${{ needs.build-and-test.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "dotnet add package affolterNET.Web.Api --version ${{ needs.build-and-test.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "dotnet add package affolterNET.Web.Bff --version ${{ needs.build-and-test.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY