name: Build and Publish NuGet Packages

on:
  push:
    branches: [ develop, main ]
    paths:
      - '**/*.csproj'
      - '**/*.cs'
      - '.github/workflows/nuget-packages.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.csproj'
      - '**/*.cs'
      - '.github/workflows/nuget-packages.yml'
  workflow_dispatch:
    inputs:
      publish_to_nuget:
        description: 'Publish to NuGet.org'
        required: false
        default: false
        type: boolean

env:
  DOTNET_VERSION: '9.0.x'
  BUILD_CONFIGURATION: 'Release'

permissions:
  contents: write       # Required to push commits back to repository
  actions: read         # Required to read workflow artifacts
  pull-requests: write  # Required to create pull requests

jobs:
  # Job 1: Version bump (only on develop branch)
  version-bump:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current version and bump
      id: bump
      run: |
        # Get current version from project file
        CURRENT_VERSION=$(grep -oP '<Version>\K[^<]+' affolterNET.Web.Core/affolterNET.Web.Core.csproj)
        echo "Found current version: '$CURRENT_VERSION'"
        
        if [ -z "$CURRENT_VERSION" ]; then
          echo "Error: Could not find current version in project file"
          exit 1
        fi
        
        # Parse version components
        MAJOR=$(echo "$CURRENT_VERSION" | cut -d'.' -f1)
        MINOR=$(echo "$CURRENT_VERSION" | cut -d'.' -f2)
        PATCH=$(echo "$CURRENT_VERSION" | cut -d'.' -f3)
        
        # Increment patch version
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        
        echo "New version: $NEW_VERSION"
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Update project versions
      run: |
        NEW_VERSION="${{ steps.bump.outputs.new_version }}"
        echo "Updating project versions to: $NEW_VERSION"
        
        # Update version in all project files
        find . -name "*.csproj" -exec sed -i "s/<Version>.*<\/Version>/<Version>$NEW_VERSION<\/Version>/g" {} \;
        
        # Display updated versions for verification
        echo "Updated project versions:"
        find . -name "*.csproj" -exec grep -H "<Version>" {} \;

    - name: Commit version changes
      run: |
        NEW_VERSION="${{ steps.bump.outputs.new_version }}"
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add and commit changes
        git add **/*.csproj
        if git diff --staged --quiet; then
          echo "No version changes to commit"
        else
          git commit -m "chore: bump version to $NEW_VERSION"
          git push origin develop
          echo "Version bumped to $NEW_VERSION on develop branch"
        fi

  # Job 2: Build and test (runs on all branches)
  build-and-test:
    runs-on: ubuntu-latest
    needs: [version-bump]
    if: always() && !cancelled() && !failure()
    
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      should_publish: ${{ steps.publish-check.outputs.should_publish }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Get current version
      id: get-version
      run: |
        # Get current version from project file
        VERSION=$(grep -oP '<Version>\K[^<]+' affolterNET.Web.Core/affolterNET.Web.Core.csproj)
        echo "Current version: '$VERSION'"
        
        if [ -z "$VERSION" ]; then
          echo "Error: Could not find current version in project file"
          exit 1
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Check if should publish
      id: publish-check
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ] && [ "${{ github.event_name }}" == "push" ]; then
          echo "should_publish=true" >> $GITHUB_OUTPUT
          echo "Will publish packages (main branch push)"
        else
          echo "should_publish=false" >> $GITHUB_OUTPUT
          echo "Will not publish packages (not main branch push)"
        fi

    - name: Restore dependencies
      run: dotnet restore

    - name: Build projects
      run: |
        dotnet build affolterNET.Web.Core/affolterNET.Web.Core.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        dotnet build affolterNET.Web.Api/affolterNET.Web.Api.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        dotnet build affolterNET.Web.Bff/affolterNET.Web.Bff.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Run tests
      run: |
        # Run tests if test projects exist
        if find . -name "*Test*.csproj" -o -name "*.Tests.csproj" | grep -q .; then
          echo "Running tests..."
          dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal --logger trx --results-directory ./test-results
        else
          echo "No test projects found, skipping tests"
        fi

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./test-results/*.trx

  # Job 3: Pack and publish (only when publishing to main)
  pack-and-publish:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: |
      needs.build-and-test.outputs.should_publish == 'true' || 
      (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_nuget == 'true')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Switch to NuGet references
      run: |
        ./switch-references.sh nuget
        echo "Switched to NuGet package references for packaging"

    - name: Build projects
      run: |
        dotnet build affolterNET.Web.Core/affolterNET.Web.Core.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        dotnet build affolterNET.Web.Api/affolterNET.Web.Api.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        dotnet build affolterNET.Web.Bff/affolterNET.Web.Bff.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Pack NuGet packages
      run: |
        VERSION="${{ needs.build-and-test.outputs.version }}"
        echo "Packing packages with version $VERSION"
        
        # Pack Core package (must be first due to dependencies)
        dotnet pack affolterNET.Web.Core/affolterNET.Web.Core.csproj \
          --configuration ${{ env.BUILD_CONFIGURATION }} \
          --no-restore \
          --no-build \
          --output ./packages \
          --include-symbols \
          --include-source \
          -p:SymbolPackageFormat=snupkg
        
        # Pack Api package
        dotnet pack affolterNET.Web.Api/affolterNET.Web.Api.csproj \
          --configuration ${{ env.BUILD_CONFIGURATION }} \
          --no-restore \
          --no-build \
          --output ./packages \
          --include-symbols \
          --include-source \
          -p:SymbolPackageFormat=snupkg
        
        # Pack Bff package
        dotnet pack affolterNET.Web.Bff/affolterNET.Web.Bff.csproj \
          --configuration ${{ env.BUILD_CONFIGURATION }} \
          --no-restore \
          --no-build \
          --output ./packages \
          --include-symbols \
          --include-source \
          -p:SymbolPackageFormat=snupkg
        
        echo "Created packages:"
        ls -la ./packages/

    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./packages/*.nupkg

    - name: Upload symbol packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-symbol-packages
        path: ./packages/*.snupkg

    - name: Publish to NuGet.org
      if: |
        needs.build-and-test.outputs.should_publish == 'true' ||
        (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_nuget == 'true')
      run: |
        echo "Publishing packages to NuGet.org..."
        for package in ./packages/*.nupkg; do
          echo "Publishing $package"
          dotnet nuget push "$package" \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
        done
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    - name: Create release summary
      run: |
        VERSION="${{ needs.build-and-test.outputs.version }}"
        echo "## NuGet Packages Published" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Version: $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Packages:" >> $GITHUB_STEP_SUMMARY
        echo "- affolterNET.Web.Core" >> $GITHUB_STEP_SUMMARY
        echo "- affolterNET.Web.Api" >> $GITHUB_STEP_SUMMARY
        echo "- affolterNET.Web.Bff" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Installation:" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo "dotnet add package affolterNET.Web.Core --version $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "dotnet add package affolterNET.Web.Api --version $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "dotnet add package affolterNET.Web.Bff --version $VERSION" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY